#!/usr/bin/env bash
set -e

help() {
    cat << EOT >&2
Activate/ deactivate mapping

USAGE
    c8y mapper mappings activation [flags]

FLAGS
    --id <string>       Id of the mapping name
    --state <boolean>   true or false

EXAMPLES
    c8y mapper mappings activation --id 1101010 --status false
    # Deactivate mapping with id 1101010
EOT
}

ARGS=()
FLAGS=()
while [ $# -gt 0 ]; do
    case "$1" in
        --status)
            STATUS="$2"
            ;;
		--id)
            ID="$2"
            ;;
        -h|--help)
            help
            exit 0
            ;;
        --*|-*)
            # Collect flags which will be passed to c8y devices create
            FLAGS+=("$1")
            ;;
    esac
    shift
done

# Validate STATUS
if [ -n "$STATUS" ]; then
    if [ "$STATUS" != "true" ] && [ "$STATUS" != "false" ]; then
        echo "Error: --status must be either 'true' or 'false'"
        exit 1
    fi
fi

set -- "${ARGS[@]}"

# echo "Set ${STATUS} on mapping ${FLAGS[@]} ${FLAGS}"

c8y inventory get --id "${ID}" | c8y inventory update --dry --template "_.SelectMerge(input.value, {'d11r_mapping':{'active': ${STATUS}}})"
