#!/usr/bin/env bash
set -e

help() {
    cat << EOT >&2
Activate/ deactivate mapping

USAGE
    c8y mapper mappings activation [flags]

FLAGS
    --id <string>       Id of the mapping name
    --state <boolean>   true or false

EXAMPLES
    c8y mapper mappings activation --id 1101010 --status false
    # Deactivate mapping with id 1101010
EOT
}

ARGS=()
FLAGS=()
while [ $# -gt 0 ]; do
    case "$1" in
        --status)
            STATUS="$2"
            ;;
        -h|--help)
            help
            exit 0
            ;;
        --*|-*)
            # Collect flags which will be passed to c8y devices create
			echo Holger "$2"
            FLAGS+=("$1" "$2")
            ;;
    esac
    shift
done

set -- "${ARGS[@]}"

# c8y util repeat --nullInput --times "${TOTAL_DEVICES:-5}" --format "$PREFIX%s%03s" \
# | c8y devices create --template mapper::device.jsonnet "${FLAGS[@]}"

echo "Set ${STATUS} on mapping ${FLAGS}"
